parameters:
#    php_memcache.class: Memcache
#    php_memcached.class: Memcached
    sfynx.cache.factory.class: Sfynx\CacheBundle\Manager\CacheFactory
    sfynx.cache.client.memcache.class: Sfynx\CacheBundle\Manager\Client\MemcacheClient
    sfynx.cache.client.filecache.class: Sfynx\CacheBundle\Manager\Client\FilecacheClient
    sfynx.cache.client.dumpercache.class: Sfynx\CacheBundle\Manager\Client\DumperClient

services:
    #
    # configuration of the class manager allowed for the filecache
    #
    sfynx.cache.dumpercache.client:
        class: '%sfynx.cache.client.dumpercache.class%'
        public: true
        arguments: ['@kernel']

    sfynx.cache.dumpercache:
        class: '%sfynx.cache.factory.class%'
        public: true
        arguments: ['@sfynx.cache.dumpercache.client']

    #
    # configuration of the class manager allowed for the filecache
    #
    sfynx.cache.filecache.client:
        class: '%sfynx.cache.client.filecache.class%'
        public: true

    sfynx.cache.filecache:
        class: '%sfynx.cache.factory.class%'
        public: true
        arguments: ['@sfynx.cache.filecache.client']


#    #
#    # configuration of the class manager allowed for the Memcache
#    #
#    php_memcache:
#        class: '%php_memcache.class%'
#
#    sfynx.cache.memcache.client:
#        class: '%sfynx.cache.client.memcache.class%'
#        arguments: ['@php_memcache']
#        calls:
#            - [ addServer, [ '%session_memcache_host%', '%session_memcache_port%' ] ]
#
#    sfynx.cache.memcache:
#        class: '%sfynx.cache.factory.class%'
#        arguments: ['@sfynx.cache.memcache.client']
#
#    # Session Configuration for memcache
#    sfynx.cache.session.memcache:
#        class: '%php_memcache.class%'
#        calls:
#             - [ addServer, [ '%session_memcache_host%', '%session_memcache_port%' ] ]
#
#    sfynx.cache.session.memcached:
#        class: '%php_memcached.class%'
#        calls:
#             - [ addServer, [ '%session_memcache_host%', '%session_memcache_port%' ] ]
#
#    pi_session.handler.memcache:
#        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcacheSessionHandler
#        arguments: [ '@sfynx.cache.session.memcache', { prefix: '%session_memcache_prefix%', expiretime: '%session_memcache_expire%' } ]
#
#    pi_session.handler.memcached:
#        class :    Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
#        arguments: [ '@sfynx.cache.session.memcached', { prefix: '%session_memcache_prefix%', expiretime: '%session_memcache_expire%'} ]
#
#    pi_session.handler.memcache.pool:
#        class:     Sfynx\CacheBundle\Session\Storage\Handler\MemcacheSessionHandler
#        arguments: [ '@sfynx.cache.session.memcache', { prefix: '%session_memcache_prefix%', expiretime: '%session_memcache_expire%', locking: '%session_memcache_locking%', spin_lock_wait: '%session_memcache_spin_lock_wait%', lock_max_wait: '%session_memcache_lock_max_wait%'} ]
